name: Run Tox tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    name: Test on Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Set up Python 🐍
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install tox tox-gh-actions coveralls
      - name: Test project with tox
        run: |
          tox
        env:
          PYTEST_ADDOPTS: --cov-config=pyproject.toml --cov --cov-append
      - name: Send coverage to coveralls
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: py-${{ matrix.python-version }}-${{ matrix.os }}

  finish:
    name: Indicate completion to coveralls.io
    runs-on: ubuntu-latest
    container: python:3-slim
    needs:
      - build
    steps:
      - name: Tell Coveralls that the parallel build is finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
